/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppBookshelfRouteImport } from './routes/app.bookshelf'
import { Route as AppBooksRouteImport } from './routes/app.books'
import { Route as AppBookIdRouteImport } from './routes/app.book.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookshelfRoute = AppBookshelfRouteImport.update({
  id: '/bookshelf',
  path: '/bookshelf',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksRoute = AppBooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => AppRoute,
} as any)
const AppBookIdRoute = AppBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/books': typeof AppBooksRoute
  '/app/bookshelf': typeof AppBookshelfRoute
  '/app/book/$id': typeof AppBookIdRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/books': typeof AppBooksRoute
  '/app/bookshelf': typeof AppBookshelfRoute
  '/app/book/$id': typeof AppBookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/books': typeof AppBooksRoute
  '/app/bookshelf': typeof AppBookshelfRoute
  '/app/book/$id': typeof AppBookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/login'
    | '/app/books'
    | '/app/bookshelf'
    | '/app/book/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/app' | '/login' | '/app/books' | '/app/bookshelf' | '/app/book/$id'
  id:
    | '__root__'
    | '/app'
    | '/login'
    | '/app/books'
    | '/app/bookshelf'
    | '/app/book/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/bookshelf': {
      id: '/app/bookshelf'
      path: '/bookshelf'
      fullPath: '/app/bookshelf'
      preLoaderRoute: typeof AppBookshelfRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/books': {
      id: '/app/books'
      path: '/books'
      fullPath: '/app/books'
      preLoaderRoute: typeof AppBooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/book/$id': {
      id: '/app/book/$id'
      path: '/book/$id'
      fullPath: '/app/book/$id'
      preLoaderRoute: typeof AppBookIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBooksRoute: typeof AppBooksRoute
  AppBookshelfRoute: typeof AppBookshelfRoute
  AppBookIdRoute: typeof AppBookIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBooksRoute: AppBooksRoute,
  AppBookshelfRoute: AppBookshelfRoute,
  AppBookIdRoute: AppBookIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
